### ISSUE TITLE
运行web端报错 Type 'TapDragUpDetails' not found.

### ISSUE THREAD

**Issue by oyanglun000** [bravekingzhang/flutter_chat_box#29]
../../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: Type 'TapDragUpDetails' not found.
  void onSingleTapUp(TapDragUpDetails details) {
                     ^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_color_scheme.dart:7788:20: Error: Type argument 'VisualDensity' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'VisualDensity' is from 'package:flutter/src/material/theme_data.dart' ('../../../../tool/flutter/packages/flutter/lib/src/material/theme_data.dart').
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<VisualDensity>('visualDensity', visualDensity));
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4139:20: Error: Type argument 'FlexAdaptive' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'FlexAdaptive' is from 'package:flex_color_scheme/src/flex_adaptive.dart' ('../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_adaptive.dart').
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<FlexAdaptive>(
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4141:20: Error: Type argument 'FlexAdaptive' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'FlexAdaptive' is from 'package:flex_color_scheme/src/flex_adaptive.dart' ('../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_adaptive.dart').
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<FlexAdaptive>(
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4143:20: Error: Type argument 'FlexAdaptive' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'FlexAdaptive' is from 'package:flex_color_scheme/src/flex_adaptive.dart' ('../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_adaptive.dart').
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<FlexAdaptive>(
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4146:14: Error: Type argument 'FlexAdaptive' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'FlexAdaptive' is from 'package:flex_color_scheme/src/flex_adaptive.dart' ('../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_adaptive.dart').
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
        .add(EnumProperty<FlexAdaptive>('adaptiveRadius', adaptiveRadius));
             ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4461:20: Error: Type argument 'double' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<double>('bottomNavigationBarSelectedIconSize',
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4463:20: Error: Type argument 'double' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<double>('bottomNavigationBarUnselectedIconSize',
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4555:20: Error: Type argument 'double' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<double>(
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/flex_color_scheme-7.1.2/lib/src/flex_sub_themes_data.dart:4557:20: Error: Type argument 'double' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    properties.add(EnumProperty<double>(
                   ^
../../../../tool/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2247:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
../../../../.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/extension_navigation.dart:222:62: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../../tool/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                  TextStyle(color: confirmTextColor ?? theme.backgroundColor),
                                                             ^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: 'TapDragUpDetails' isn't a type.
  void onSingleTapUp(TapDragUpDetails details) {
                     ^^^^^^^^^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///Users/gougou/.pub-cache/hosted/pub.dev/flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart, which contains the type: FunctionType(void Function(<invalid>)).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3236)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3197)
#2      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1570)
#3      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:962)
#4      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#5      List.forEach (dart:core-patch/growable_array.dart:416)
#6      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#7      List.forEach (dart:core-patch/growable_array.dart:416)
#8      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#9      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#10     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:801)
<asynchronous suspension>
#11     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:661)
<asynchronous suspension>
#12     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1311)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.

**Comment by oyanglun000** [comment]
我现在web是跑起来了，但一直无法加载数据，点击设置按钮会报错
